### PR TITLE
Make discovery of current name optional

### LINKED ISSUE #10: Option to disable nameless-current-name
I tried doing this in a hook, but apparently it's impossible to avoid. In Spacemacs (which seems to be my go-to example) we have e.g. `init.el` which contains references to the variable `init-file-debug`, which seems like a case where I _don't_ want nameless to do its thing.

At least for me, `nameless-global-aliases` is sufficient for what I want to do, and I don't need an auto-discovered extra alias.

### PR DESCRIPTION
**Pull request by TheBB**
- Don't crash in buffers where the current name cannot be found. This allows nameless to continue with just global and local aliases.
- Don't discover the current name if `nameless-discover-current-name` is nil.

Fixes #10. Let me know what you think!

### CODE REVIEW

**Comment by Malabarba** [comment]
Awesome. This is something I've been wanting to do as well.
On a quick read it looks good. I'll read the diff more carefully when I get home and merge. :+1: 
Thanks!

**Comment by Malabarba** [comment]
Merged. Thanks again!

**Comment by TheBB** [comment]
No worries, thanks for a nice package!

**Comment by TheBB** [comment]
No worries, thanks for a nice package!

**Pull request merged**
